/*
 * Licensed under MIT (https://github.com/ligoj/ligoj/blob/master/LICENSE)
 */
callback({
   "config":{
      "regions":[
         {
            "region":"eu-ireland",
            "instanceTypes":[
               {
                  "type":"generalCurrentGen",
                  "sizes":[
                     {
                        "size":"c1.medium",
                        "valueColumns":[
                           {
                              "name":"linux",
                              "prices":{
                                 "USD":"AAAAAA"
                              }
                           }
                        ]
                     }
                    ]
               }
           ]
         }
      ]
   }
});